# Generated by Django 3.1.6 on 2021-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210307_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
