# Generated by Django 3.1.6 on 2021-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='thumbnail/'),
        ),
    ]
