# Generated by Django 3.1.6 on 2021-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210502_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_info',
            name='fblink',
        ),
        migrations.RemoveField(
            model_name='extra_info',
            name='twtrlink',
        ),
        migrations.AddField(
            model_name='extra_info',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='extra_info',
            name='gthb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='extra_info',
            name='inst_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='extra_info',
            name='twtr_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='extra_info',
            name='site_link',
            field=models.URLField(blank=True),
        ),
    ]
